# -*- coding: utf-8 -*-
"""2.List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1xPJ-cFFd9En7pL5T2FDoX1mkKOPKFD
"""

#Masud1860
"""
Let a given list is-> a = [1, 3, 5, 7, 4]
"""
# Initial list
a = [1, 3, 5, 7, 4]

# 1) Access a[-2] (second last element) and a[2] (third element)
print(a[-2])  # Output: 7
print(a[2])   # Output: 5

# 2) Find the length and type of the list
print(len(a))  # Output: 5 (number of elements in the list)
print(type(a))  # Output: <class 'list'>

# 3) Modify elements in the list
a[-3] = 50  # Replace the third last element with 50
print(a[-3])  # Output: 50
print(a)  # Output: [1, 3, 50, 7, 4]

# a[2:4] refers to a slice of the list. Modifying this directly doesn't replace a single element.
# Correction: Assigning the slice `[50]` to `a[2:4]`
a[2:4] = [50]
print(a)  # Output: [1, 3, 50, 4]

# 4) Add 100 to the last index
a.append(100)  # Append 100 at the end of the list
print(a)  # Output: [1, 3, 50, 4, 100]

# 5) Join a new list [2, 4, 6] with a
a.extend([2, 4, 6])  # Extend the list `a` with `[2, 4, 6]`
print(a)  # Output: [1, 3, 50, 4, 100, 2, 4, 6]

# 6) Copy all values of `a` into a new list `b`
b = a.copy()  # Create a copy of list `a`
print(b)  # Output: [1, 3, 50, 4, 100, 2, 4, 6]

# 7) Sort the elements of list `b`
b.sort()  # Sorts `b` in ascending order
print(b)  # Output: [1, 2, 3, 4, 4, 6, 50, 100]

# 8) Print all elements of `a` using a loop, and break if the element is 5
for item in a:
    if item == 5:  # Check if the current item is 5
        break
    print(item)  # Print the item until 5 is encountered

# 9) Find the largest number in `a`
print(max(a))  # Output: 100